name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.11] # Avoid Python 3.12 for now
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set working directory
        run: cd $GITHUB_WORKSPACE/docsum-vim  # Make sure the working directory is set to the root of your repo
      - name: Run tests
        run: |
          python3 docsum.py docs/declaration
          python3 docsum.py docs/2023.findings-emnlp.945.pdf
          python3 docsum.py docs/estados-unidos-admite-haber-perdido-la-pista-de-32000-menores-migrantes-no-acompanados.html
          python3 docsum.py docs/news-mx.txt
          python3 docsum.py docs/constitution-mx.txt

